yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutMePage.as_view(), name='me'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.post_create, name='post_create'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/<int:post_id>/', views.post_detail, name='post_detail'),
    path('<username>/<int:post_id>/edit/', views.post_edit, name='post_edit')
]

yatube/users/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.LoginView.as_view(
            template_name='users/login.html',
            redirect_field_name='posts:profile'
        ),
        name='login'
    ),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('staff/admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
import textwrap

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Название группы'
    )
    slug = models.SlugField('Адрес', unique=True, help_text='Адрес группы')
    description = models.TextField('Описание', help_text='Описание группы')

    class Meta:
        verbose_name = 'Группа'

    def __str__(self):
        return str(self.title)


class Post(models.Model):
    text = models.TextField('Текст', help_text='Текст поста')
    pub_date = models.DateTimeField(
        'Дата пуликации',
        auto_now_add=True,
        help_text='Дата публикации поста'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Связанная группа'
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'Пост'

    def __str__(self):
        fullname = self.author.get_full_name()
        slug = self.author.username
        res = f'Автор: {fullname} ({slug})\n'
        res += f'Группа: {self.group}\n'
        res += f'Дата публикации: {self.pub_date.date()}\n'
        shorten_text = textwrap.shorten(
            text=self.text,
            width=20,
            placeholder='...'
        )
        res += f'Текст: {shorten_text}'
        return res

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class TechPage(TemplateView):
    template_name = 'about/tech.html'


class AboutMePage(TemplateView):
    template_name = 'about/author.html'

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Group, Post
from yatube.settings import ELEMENTS_PER_PAGE

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'group': group,
        'page': page
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'author': author,
        'page': page,
    }
    return render(request, template, context)


def post_detail(request, username, post_id):
    template = 'posts/post_detail.html'
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, pk=post_id)
    context = {
        'author': author,
        'post': post
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        Post.objects.create(
            text=form.cleaned_data['text'],
            author=request.user,
            group=form.cleaned_data['group'])
        return redirect('posts:index')
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, pk=post_id)
    if request.user != author:
        return redirect('posts:post_detail', author.username, post_id)
    form = PostForm(request.POST or None)
    if request.method == 'GET':
        form.fields['text'].initial = post.text
        form.fields['group'].initial = post.group
        return render(request, 'posts/create_post.html',
                      {'is_edit': True, 'form': form})
    if form.is_valid():
        post.text = form.cleaned_data['text']
        post.group = form.cleaned_data['group']
        post.save()
        return redirect('posts:post_detail', author.username, post_id)
    return render(request, 'posts/create_post.html',
                  {'is_edit': True, 'form': form})

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends 'base.html' %}
{% block title %}
  Обо мне любимом
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Обо мне любимом</h1>
    Лучше помолчать
  </div>
{% endblock %}

yatube/templates/about/tech.html
{% extends 'base.html' %}
{% block title %}
  Технологии
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Технологии</h1>
    ЭВМ
  </div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href={% static "img/fav/fav.ico" %} type="image">
    <link rel="apple-touch-icon" sizes="180x180" href={% static "img/fav/apple-touch-icon.png" %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static "img/fav/favicon-32x32.png" %}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static "img/fav/favicon-16x16.png" %}>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}Заголовок потерялся{% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}    
    </header>
    <main>

      {% block content %}
        <div class="container">
          Контент ушел погулять
        </div>
      {% endblock %}

    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}    
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %} 
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbar-example" aria-controls="navbar-example"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% include 'includes/nav.html' %}  
  </div>
</nav>   

yatube/templates/includes/nav.html
{% comment %}
Выпадающее меню пока не работает. Так задумано (пока что)
{% endcomment %}
{% with request.resolver_match.view_name as view_name %}
<div class="collapse navbar-collapse" id="navbar-example">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"> 
      <a class="nav-link {% if view_name  == 'about:me' %}active{% endif %}" 
        href="{% url 'about:me' %}">
        Об авторе
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
        href="{% url 'about:tech' %}">
        Технологии
      </a>
    </li>
    {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link " 
          href="{% url 'posts:post_create' %}">
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
          href="{% url 'users:password_change' %}">
          Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">
          Выйти
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'posts:profile' %}active{% endif %}" 
          href="{% url 'posts:profile' user.username %}">
          Пользователь: {{ user.username }}.
        </a>
      </li>
    {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">
          Регистрация
        </a>
      </li>
    {% endif %}
  </ul>
</div>
{% endwith %} 

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load custom_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
              {% endif %}
              <div class="card-body">        
                <form method="post" action="{% url 'posts:post_create' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/group.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }} | Yatube
{% endblock %}
{% block content %} 
  <div class="container py-5"> 
    <h1>{{ group }}</h1> 
    <p> 
      {{ group.description }} 
    </p> 
    {% for post in page %} 
      <article> 
        <ul> 
          <li> 
            {% include 'posts/includes/author_card.html'%}
          </li> 
          <li> 
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li> 
        </ul> 
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.author.username post.pk %}">подробная инормация </a>
      </article> 
      <hr>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %}  

yatube/templates/posts/includes/author_card.html
Автор: {{ post.author.get_full_name }}
(<a href="{% url 'posts:profile' post.author.username %}">{{ post.author.username }}</a>)

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page %}
      <ul>
        <li>
          {% include 'posts/includes/author_card.html'%}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.author.username post.pk %}">подробная инормация </a>
      <br>
      {% if post.group %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы {{ post.group.title }}</a>
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}
  Пост {{ post.text|maketitle }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: 
            <a href="{% url 'posts:group' post.group.slug %}">
              {{ post.group.title }}
            </a>
          </li>
        {% endif %}
              
        <li class="list-group-item">
          {% include 'posts/includes/author_card.html'%}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text }}
      </p>
      {% if user == author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' author.username post.pk %}">
        редактировать запись
      </a>
      {% endif %}
    </article>
  </div> 
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Все посты пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>   
      {% for post in page %}
      <article> 
        <ul>
          <li>
            {% include 'posts/includes/author_card.html'%}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.author.username post.pk %}">подробная информация </a>
      </article> 
      {% if post.group != Null %}
        {% if post.group != '' %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы {{ post.group.title }}</a>
        {% endif %}
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Вы вышли из системы</div>
        <div class="card-body">
          <p> Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}

{% block content %}
  {% load custom_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              Имя пользователя и пароль не совпадают. Введите правильные данные.
            </div>
          {% endif %}

          {% if next %}
            <div class="alert alert-info" role="alert">
              Вы обратились к странице, доступ к которой возможен
              только для залогиненных пользователей.<br>
              Пожалуйста, авторизуйтесь.
            </div>
          {% else %}
            <div class="alert alert-info" role="alert">
              Пожалуйста, авторизуйтесь.
            </div>
          {% endif %}

          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="form-group row">
              <label
                for="{{ form.username.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Имя пользователя
              </label>
              <div class="col-md-6">
                {{ form.username }}
              </div>
            </div>

            <div class="form-group row">
              <label
                for="{{ form.password.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Пароль
              </label>
              <div class="col-md-6">
                {{ form.password }}
              </div>
            </div>

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
  {% load custom_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  <span class="required">*</span>
                </label>
                <div class="col-md-6">
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>

        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля выполнен{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Сброс пароля выполнен</div>
        <div class="card-body">
          <p>Пароль изменён, всё получилось.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}

{% block content %}
  {% load custom_filters %}
  {% if validlink %}

    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">

            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
            {% endif %}

            <form method="post">
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  <span class="required">*</span>
                </label>
                <div class="col-md-6">
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
              {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
            </form>

          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->

  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Ссылка на восстановление пароля отправлена{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ссылка на восстановление пароля отправлена</div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {% load custom_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}